# Yureka Server Configuration
server:
  port: 8762   # HTTP port
spring: 
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl: 
      defaultZone: http://peer2:8763/eureka
    registerWithEureka: true
    fetchRegistry: true
